spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    topics:
      order-events: order-events
      order-events-dlq: order-events-dlq

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

